version: '3.4'

x-common-variables: &variables
  NETWORK: "simnet"

services:
  dcrd:
    build:
      context: dcrd/
    environment: *variables
    volumes:
      - shared:/rpc
      - decred:/data
    networks:
      - ln-network

  dcrwallet:
    build: dcrwallet/
    depends_on:
      - dcrd
    environment: *variables
    volumes:
      - shared:/rpc
    networks:
      - ln-network

volumes:
  shared:
    driver: local
  decred:
    driver: local
networks:
  ln-network:
    driver: bridge
